name: Build APK
on: [push]

permissions:
  actions: write  # Required for artifact uploads

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-17-jdk
          pip install buildozer
      - name: Build APK
        run: |
          buildozer android debug
          mkdir -p apk
          cp bin/*.apk apk/
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: vision2text-apk
          path: apk/*.apk
