name: Build APK
on: [push]

permissions:
  actions: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            openjdk-17-jdk \
            zlib1g-dev \
            libncurses5-dev \
            libffi-dev \
            libssl-dev
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython virtualenv
          
      - name: Build APK (with debug output)
        run: |
          buildozer init
          buildozer -v android debug 2>&1 | tee build.log
          ls -la bin/ || true
          
      - name: Upload APK
        if: success() && contains(fromJson('["debug","release"]'), 'debug')
        uses: actions/upload-artifact@v4
        with:
          name: vision2text-apk
          path: bin/*.apk
          
      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
